# Generated by Django 5.2.17 on 2026-09-30 23:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nome')),
                ('level', models.PositiveSmallIntegerField(help_text='De 1 (mais fácil) a 3 (mais difícil).', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='nível')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'dificuldade',
                'verbose_name_plural': 'dificuldades',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'equipamento',
                'verbose_name_plural': 'equipamentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MuscularGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'grupo muscular',
                'verbose_name_plural': 'grupos musculares',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('tip', models.TextField(blank=True, verbose_name='dica de execução')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='URL do vídeo')),
                ('is_equipment_free', models.BooleanField(default=False, help_text='Marque se o exercício pode ser feito sem nenhum aparelho.', verbose_name='sem equipamento')),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='exercises.difficulty', verbose_name='dificuldade')),
                ('equipment', models.ManyToManyField(blank=True, related_name='exercises', to='exercises.equipment', verbose_name='equipamentos')),
            ],
            options={
                'verbose_name': 'exercício',
                'verbose_name_plural': 'exercícios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Números menores aparecem primeiro.', verbose_name='ordem')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_of_links', to='exercises.exercise', verbose_name='alternativa')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_links', to='exercises.exercise', verbose_name='exercício')),
            ],
            options={
                'verbose_name': 'alternativa de exercício',
                'verbose_name_plural': 'alternativas de exercícios',
                'ordering': ['exercise', 'order'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='alternatives',
            field=models.ManyToManyField(related_name='alternative_to', through='exercises.ExerciseAlternative', through_fields=('exercise', 'alternative'), to='exercises.exercise', verbose_name='alternativas'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscular_groups',
            field=models.ManyToManyField(related_name='exercises', to='exercises.musculargroup', verbose_name='grupos musculares'),
        ),
        migrations.AddConstraint(
            model_name='exercisealternative',
            constraint=models.UniqueConstraint(fields=('exercise', 'alternative'), name='unique_exercise_alternative'),
        ),
        migrations.AddConstraint(
            model_name='exercisealternative',
            constraint=models.CheckConstraint(condition=models.Q(('exercise', models.F('alternative')), _negated=True), name='alternative_is_not_itself'),
        ),
    ]
