# Generated by Django 5.2.17 on 2026-10-09 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'padrão de movimento',
                'verbose_name_plural': 'padrões de movimento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='autor / organização')),
                ('title', models.CharField(max_length=500, verbose_name='título')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('source_type', models.CharField(blank=True, max_length=150, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'fonte',
                'verbose_name_plural': 'fontes',
                'ordering': ['author', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='is_equipment_free',
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(blank=True, choices=[('free_weight', 'Peso livre'), ('accessory', 'Acessório'), ('fixed_structure', 'Estrutura fixa'), ('machine', 'Máquina')], max_length=20, verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='data_status',
            field=models.CharField(blank=True, choices=[('sourced', 'Com fonte'), ('lucas_unsourced', 'Sem fonte - dado do Lucas'), ('needs_review', 'Sem fonte específica (revisar)')], max_length=30, verbose_name='status dos dados'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='nome em inglês'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observação interna'),
        ),
        migrations.AddField(
            model_name='exercisealternative',
            name='note',
            field=models.TextField(blank=True, help_text='Comentário sobre esta troca específica.', verbose_name='observação'),
        ),
        migrations.AddField(
            model_name='musculargroup',
            name='code',
            field=models.CharField(blank=True, help_text='Identificador sem acentos, ex.: POSTERIOR_COXA.', max_length=50, verbose_name='código'),
        ),
        migrations.AddField(
            model_name='musculargroup',
            name='region',
            field=models.CharField(blank=True, choices=[('upper', 'Superior'), ('core', 'Core'), ('lower', 'Inferior')], max_length=20, verbose_name='região'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.ManyToManyField(blank=True, help_text='Deixe vazio se o exercício não usa nenhum objeto (só o corpo, o chão ou a parede).', related_name='exercises', to='exercises.equipment', verbose_name='equipamentos'),
        ),
        migrations.CreateModel(
            name='ExerciseAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=150, unique=True, verbose_name='apelido')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='exercises.exercise', verbose_name='exercício')),
            ],
            options={
                'verbose_name': 'apelido',
                'verbose_name_plural': 'apelidos',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseMuscularGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Principal'), ('secondary', 'Auxiliar')], default='primary', max_length=20, verbose_name='papel')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscular_group_links', to='exercises.exercise', verbose_name='exercício')),
                ('muscular_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_links', to='exercises.musculargroup', verbose_name='grupo muscular')),
            ],
            options={
                'verbose_name': 'grupo muscular do exercício',
                'verbose_name_plural': 'grupos musculares do exercício',
                'ordering': ['exercise', 'role', 'muscular_group__name'],
            },
        ),
        # O Django não converte uma ligação N-N simples em uma ligação com tabela
        # intermediária (through). Por isso a ligação antiga é removida e a nova
        # é criada; os dados de grupos são recarregados pelo importar_planilha.
        migrations.RemoveField(
            model_name='exercise',
            name='muscular_groups',
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscular_groups',
            field=models.ManyToManyField(related_name='exercises', through='exercises.ExerciseMuscularGroup', to='exercises.musculargroup', verbose_name='grupos musculares'),
        ),
        migrations.CreateModel(
            name='ExerciseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ordem')),
                ('description', models.TextField(verbose_name='descrição')),
                ('extra_tip', models.TextField(blank=True, verbose_name='dica extra')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='exercises.exercise', verbose_name='exercício')),
            ],
            options={
                'verbose_name': 'passo de execução',
                'verbose_name_plural': 'passos de execução',
                'ordering': ['exercise', 'order'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='exercises.movementpattern', verbose_name='padrão de movimento'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='exercises.source', verbose_name='fontes'),
        ),
        migrations.AddConstraint(
            model_name='exercisemusculargroup',
            constraint=models.UniqueConstraint(fields=('exercise', 'muscular_group'), name='unique_exercise_muscular_group'),
        ),
        migrations.AddConstraint(
            model_name='exercisestep',
            constraint=models.UniqueConstraint(fields=('exercise', 'order'), name='unique_exercise_step_order'),
        ),
    ]
